exports.seed = (knex, Promise) => {
  return knex('jobs').insert([
    {
      id: 0,
      date_created: new Date(Date.now()),
      img: './img/houses/SS Alexandra',
      jobName: 'Alexandra',
      collection: 'Southern Series',
      client: 'Jennian Standard Pricing',
      jobNumber: 'SS01',
      siteAddress: 'none',
      lotNumber: 'none',
      gfa: '170.69m2'
    },
    {
      id: 1,
      date_created: new Date(Date.now()),
      img: './img/houses/SS Alexandra Architectural',
      jobName: 'Alexandra Architectural',
      collection: 'Southern Series',
      client: 'Jennian Standard Pricing',
      jobNumber: 'SS01a',
      siteAddress: 'none',
      lotNumber: 'none',
      gfa: '170.69m2'
    },
    {
      id: 2,
      date_created: new Date(Date.now()),
      img: './img/houses/SS Andrew',
      jobName: 'Andrew',
      collection: 'Southern Series',
      client: 'Jennian Standard Pricing',
      jobNumber: 'SS02',
      siteAddress: 'none',
      lotNumber: 'none',
      gfa: '154.60m2'
    },
    {
      id: 3,
      date_created: new Date(Date.now()),
      img: './img/houses/SS Andrew Architectural',
      jobName: 'Andrew Architectural',
      collection: 'Southern Series',
      client: 'Jennian Standard Pricing',
      jobNumber: 'SS02a',
      siteAddress: 'none',
      lotNumber: 'none',
      gfa: '154.60m2'
    },
    {
      id: 4,
      date_created: new Date(Date.now()),
      img: './img/houses/SS Anne',
      jobName: 'Anne',
      collection: 'Southern Series',
      client: 'Jennian Standard Pricing',
      jobNumber: 'SS03',
      siteAddress: 'none',
      lotNumber: 'none',
      gfa: '166.61m2'
    },
    {
      id: 5,
      date_created: new Date(Date.now()),
      img: './img/houses/SS Anne Architectural',
      jobName: 'Anne Architectural',
      collection: 'Southern Series',
      client: 'Jennian Standard Pricing',
      jobNumber: 'SS03a',
      siteAddress: 'none',
      lotNumber: 'none',
      gfa: '166.61m2'
    },
    {
      id: 6,
      jobName: 'Cathrine',
      date_created: new Date(Date.now()),
      img: './img/houses/SS Cathrine',
      collection: 'Southern Series',
      client: 'Jennian Standard Pricing',
      jobNumber: 'SS04',
      siteAddress: 'none',
      lotNumber: 'none',
      gfa: '111.08m2'
    },
    {
      id: 7,
      date_created: new Date(Date.now()),
      img: './img/houses/SS Cathrine Architectural',
      jobName: 'Cathrine Architectural',
      collection: 'Southern Series',
      client: 'Jennian Standard Pricing',
      jobNumber: 'SS04a',
      siteAddress: 'none',
      lotNumber: 'none',
      gfa: '111.08m2'
    },
    {
      id: 8,
      date_created: new Date(Date.now()),
      img: './img/houses/SS Charles',
      jobName: 'Charles',
      collection: 'Southern Series',
      client: 'Jennian Standard Pricing',
      jobNumber: 'SS05',
      siteAddress: 'none',
      lotNumber: 'none',
      gfa: '181.78m2'
    },
    {
      id: 9,
      date_created: new Date(Date.now()),
      img: './img/houses/SS Charles Architectural',
      jobName: 'Charles Architectural',
      collection: 'Southern Series',
      client: 'Jennian Standard Pricing',
      jobNumber: 'SS05a',
      siteAddress: 'none',
      lotNumber: 'none',
      gfa: '181.78m2'
    },
    {
      id: 10,
      jobName: 'Charlotte',
      date_created: new Date(Date.now()),
      img: './img/houses/SS Charlotte',
      collection: 'Southern Series',
      client: 'Jennian Standard Pricing',
      jobNumber: 'SS06',
      siteAddress: 'none',
      lotNumber: 'none',
      gfa: '135.37m2'
    },
    {
      id: 11,
      date_created: new Date(Date.now()),
      img: './img/houses/SS Charlotte Architectural',
      jobName: 'Charlotte Architectural',
      collection: 'Southern Series',
      client: 'Jennian Standard Pricing',
      jobNumber: 'SS06a',
      siteAddress: 'none',
      lotNumber: 'none',
      gfa: '135.37m2'
    },
    {
      id: 12,
      date_created: new Date(Date.now()),
      img: './img/houses/SS Edward 2',
      jobName: 'Edward 2',
      collection: 'Southern Series',
      client: 'Jennian Standard Pricing',
      jobNumber: 'SS07',
      siteAddress: 'none',
      lotNumber: 'none',
      gfa: '106.41m2'
    },
    {
      id: 13,
      date_created: new Date(Date.now()),
      img: './img/houses/SS Edward 3',
      jobName: 'Edward 3',
      collection: 'Southern Series',
      client: 'Jennian Standard Pricing',
      jobNumber: 'SS08',
      siteAddress: 'none',
      lotNumber: 'none',
      gfa: '120.22m2'
    },
    {
      id: 14,
      date_created: new Date(Date.now()),
      img: './img/houses/SS Edaward 3 Architectural',
      jobName: 'Edward 3 Architectural',
      collection: 'Southern Series',
      client: 'Jennian Standard Pricing',
      jobNumber: 'SS08a',
      siteAddress: 'none',
      lotNumber: 'none',
      gfa: '120.64m2'
    },
    {
      id: 15,
      date_created: new Date(Date.now()),
      img: './img/houses/SS Edward 4',
      jobName: 'Edward 4',
      collection: 'Southern Series',
      client: 'Jennian Standard Pricing',
      jobNumber: 'SS09',
      siteAddress: 'none',
      lotNumber: 'none',
      gfa: '132.71m2'
    },
    {
      id: 16,
      date_created: new Date(Date.now()),
      img: './img/houses/SS Ernest',
      jobName: 'Ernest',
      collection: 'Southern Series',
      client: 'Jennian Standard Pricing',
      jobNumber: 'SS10',
      siteAddress: 'none',
      lotNumber: 'none',
      gfa: '167.62m2'
    },
    {
      id: 17,
      date_created: new Date(Date.now()),
      img: './img/houses/SS George',      
      jobName: 'George',
      collection: 'Southern Series',
      client: 'Jennian Standard Pricing',
      jobNumber: 'SS11',
      siteAddress: 'none',
      lotNumber: 'none',
      gfa: '166.04m2'
    },
    {
      id: 18,
      date_created: new Date(Date.now()),
      img: './img/houses/SS George Architectural',      
      jobName: 'George Architectural',
      collection: 'Southern Series',
      client: 'Jennian Standard Pricing',
      jobNumber: 'SS11a',
      siteAddress: 'none',
      lotNumber: 'none',
      gfa: '166.04m2'
    },
    {
      id: 19,
      date_created: new Date(Date.now()),
      img: './img/houses/SS James',      
      jobName: 'James',
      collection: 'Southern Series',
      client: 'Jennian Standard Pricing',
      jobNumber: 'SS12',
      siteAddress: 'none',
      lotNumber: 'none',
      gfa: '164.84m2'
    },
    {
      id: 20,
      date_created: new Date(Date.now()),
      img: './img/houses/SS James Architectural',      
      jobName: 'James Architectural',
      collection: 'Southern Series',
      client: 'Jennian Standard Pricing',
      jobNumber: 'SS12a',
      siteAddress: 'none',
      lotNumber: 'none',
      gfa: '164.84m2'
    },
    {
      id: 21,
      date_created: new Date(Date.now()),
      img: './img/houses/SS Louis',      
      jobName: 'Louis',
      collection: 'Southern Series',
      client: 'Jennian Standard Pricing',
      jobNumber: 'SS13',
      siteAddress: 'none',
      lotNumber: 'none',
      gfa: '157.98m2'
    },
    {
      id: 22,
      date_created: new Date(Date.now()),
      img: './img/houses/SS Louis Architectural',      
      jobName: 'Louis Architectural',
      collection: 'Southern Series',
      client: 'Jennian Standard Pricing',
      jobNumber: 'SS13a',
      siteAddress: 'none',
      lotNumber: 'none',
      gfa: '157.98m2'
    },
    {
      id: 23,
      date_created: new Date(Date.now()),
      img: './img/houses/SS Louis 2 Architectural',      
      jobName: 'Louis 2 Architectural',
      collection: 'Southern Series',
      client: 'Jennian Standard Pricing',
      jobNumber: 'SS13a2',
      siteAddress: 'none',
      lotNumber: 'none',
      gfa: '157.98m2'
    },
    {
      id: 24,
      date_created: new Date(Date.now()),
      img: './img/houses/SS Louis 3 Architectural',      
      jobName: 'Louis 3 Architectural',
      collection: 'Southern Series',
      client: 'Jennian Standard Pricing',
      jobNumber: 'SS13a3',
      siteAddress: 'none',
      lotNumber: 'none',
      gfa: '157.98m2'
    },
    {
      id: 25,
      date_created: new Date(Date.now()),
      img: './img/houses/SS Mary',      
      jobName: 'Mary',
      collection: 'Southern Series',
      client: 'Jennian Standard Pricing',
      jobNumber: 'SS14',
      siteAddress: 'none',
      lotNumber: 'none',
      gfa: '165.25m2'
    },
    {
      id: 26,
      date_created: new Date(Date.now()),
      img: './img/houses/SS Mary Architectural',      
      jobName: 'Mary Architectural',
      collection: 'Southern Series',
      client: 'Jennian Standard Pricing',
      jobNumber: 'SS14a',
      siteAddress: 'none',
      lotNumber: 'none',
      gfa: '165.25m2'
    },
    {
      id: 27,
      date_created: new Date(Date.now()),
      img: './img/houses/SS Victora',      
      jobName: 'Victora',
      collection: 'Southern Series',
      client: 'Jennian Standard Pricing',
      jobNumber: 'SS15',
      siteAddress: 'none',
      lotNumber: 'none',
      gfa: '180.97m2'
    },
    {
      id: 28,
      date_created: new Date(Date.now()),
      img: './img/houses/SS Victora Architectural',      
      jobName: 'Victora Architectural',
      collection: 'Southern Series',
      client: 'Jennian Standard Pricing',
      jobNumber: 'SS15a',
      siteAddress: 'none',
      lotNumber: 'none',
      gfa: '180.97m2'
    },
    {
      id: 29,
      date_created: new Date(Date.now()),
      img: './img/houses/SS William',      
      jobName: 'William',
      collection: 'Southern Series',
      client: 'Jennian Standard Pricing',
      jobNumber: 'SS16',
      siteAddress: 'none',
      lotNumber: 'none',
      gfa: '201.97m2'
    },
    {
      id: 30,
      date_created: new Date(Date.now()),
      img: './img/houses/SS William Architectural',      
      jobName: 'William Architectural',
      collection: 'Southern Series',
      client: 'Jennian Standard Pricing',
      jobNumber: 'SS16a',
      siteAddress: 'none',
      lotNumber: 'none',
      gfa: '201.97m2'
    },
  ])
}




