exports.seed = (knex, Promise) => {
  return knex('jobs').insert([
    {
      id: 0,
      date_created: new Date(Date.now()),
      img: 'img/houses/SS_Alexandra.png',
      jobName: 'Alexandra',
      collection: 'Southern Series',
      client: 'Jennian Standard Pricing',
      jobNumber: 'SS01',
      siteAddress: 'none',
      lotNumber: 'none',
      gfa: '170.69m2'
    },
    {
      id: 1,
      date_created: new Date(Date.now()),
      img: 'img/houses/SS Alexandra Architectural.png',
      jobName: 'Alexandra Architectural',
      collection: 'Southern Series',
      client: 'Jennian Standard Pricing',
      jobNumber: 'SS01a',
      siteAddress: 'none',
      lotNumber: 'none',
      gfa: '170.69m2'
    },
    {
      id: 2,
      date_created: new Date(Date.now()),
      img: 'img/houses/SS Andrew.png',
      jobName: 'Andrew',
      collection: 'Southern Series',
      client: 'Jennian Standard Pricing',
      jobNumber: 'SS02',
      siteAddress: 'none',
      lotNumber: 'none',
      gfa: '154.60m2'
    },
    {
      id: 3,
      date_created: new Date(Date.now()),
      img: 'img/houses/SS Andrew Architectural.png',
      jobName: 'Andrew Architectural',
      collection: 'Southern Series',
      client: 'Jennian Standard Pricing',
      jobNumber: 'SS02a',
      siteAddress: 'none',
      lotNumber: 'none',
      gfa: '154.60m2'
    },
    {
      id: 4,
      date_created: new Date(Date.now()),
      img: 'img/houses/SS Anne.png',
      jobName: 'Anne',
      collection: 'Southern Series',
      client: 'Jennian Standard Pricing',
      jobNumber: 'SS03',
      siteAddress: 'none',
      lotNumber: 'none',
      gfa: '166.61m2'
    },
    {
      id: 5,
      date_created: new Date(Date.now()),
      img: 'img/houses/SS Anne Architectural.png',
      jobName: 'Anne Architectural',
      collection: 'Southern Series',
      client: 'Jennian Standard Pricing',
      jobNumber: 'SS03a',
      siteAddress: 'none',
      lotNumber: 'none',
      gfa: '166.61m2'
    },
    {
      id: 6,
      jobName: 'Cathrine',
      date_created: new Date(Date.now()),
      img: 'img/houses/SS Cathrine.png',
      collection: 'Southern Series',
      client: 'Jennian Standard Pricing',
      jobNumber: 'SS04',
      siteAddress: 'none',
      lotNumber: 'none',
      gfa: '111.08m2'
    },
    {
      id: 7,
      date_created: new Date(Date.now()),
      img: 'img/houses/SS Cathrine Architectural.png',
      jobName: 'Cathrine Architectural',
      collection: 'Southern Series',
      client: 'Jennian Standard Pricing',
      jobNumber: 'SS04a',
      siteAddress: 'none',
      lotNumber: 'none',
      gfa: '111.08m2'
    },
    {
      id: 8,
      date_created: new Date(Date.now()),
      img: 'img/houses/SS Charles.png',
      jobName: 'Charles',
      collection: 'Southern Series',
      client: 'Jennian Standard Pricing',
      jobNumber: 'SS05',
      siteAddress: 'none',
      lotNumber: 'none',
      gfa: '181.78m2'
    },
    {
      id: 9,
      date_created: new Date(Date.now()),
      img: 'img/houses/SS Charles Architectural.png',
      jobName: 'Charles Architectural',
      collection: 'Southern Series',
      client: 'Jennian Standard Pricing',
      jobNumber: 'SS05a',
      siteAddress: 'none',
      lotNumber: 'none',
      gfa: '181.78m2'
    },
    {
      id: 10,
      jobName: 'Charlotte',
      date_created: new Date(Date.now()),
      img: 'img/houses/SS Charlotte.png',
      collection: 'Southern Series',
      client: 'Jennian Standard Pricing',
      jobNumber: 'SS06',
      siteAddress: 'none',
      lotNumber: 'none',
      gfa: '135.37m2'
    },
    {
      id: 11,
      date_created: new Date(Date.now()),
      img: 'img/houses/SS Charlotte Architectural.png',
      jobName: 'Charlotte Architectural',
      collection: 'Southern Series',
      client: 'Jennian Standard Pricing',
      jobNumber: 'SS06a',
      siteAddress: 'none',
      lotNumber: 'none',
      gfa: '135.37m2'
    },
    {
      id: 12,
      date_created: new Date(Date.now()),
      img: 'img/houses/SS Edward 2.png',
      jobName: 'Edward 2',
      collection: 'Southern Series',
      client: 'Jennian Standard Pricing',
      jobNumber: 'SS07',
      siteAddress: 'none',
      lotNumber: 'none',
      gfa: '106.41m2'
    },
    {
      id: 13,
      date_created: new Date(Date.now()),
      img: 'img/houses/SS Edward 3.png',
      jobName: 'Edward 3',
      collection: 'Southern Series',
      client: 'Jennian Standard Pricing',
      jobNumber: 'SS08',
      siteAddress: 'none',
      lotNumber: 'none',
      gfa: '120.22m2'
    },
    {
      id: 14,
      date_created: new Date(Date.now()),
      img: 'img/houses/SS Edaward 3 Architectural.png',
      jobName: 'Edward 3 Architectural',
      collection: 'Southern Series',
      client: 'Jennian Standard Pricing',
      jobNumber: 'SS08a',
      siteAddress: 'none',
      lotNumber: 'none',
      gfa: '120.64m2'
    },
    {
      id: 15,
      date_created: new Date(Date.now()),
      img: 'img/houses/SS Edward 4.png',
      jobName: 'Edward 4',
      collection: 'Southern Series',
      client: 'Jennian Standard Pricing',
      jobNumber: 'SS09',
      siteAddress: 'none',
      lotNumber: 'none',
      gfa: '132.71m2'
    },
    {
      id: 16,
      date_created: new Date(Date.now()),
      img: 'img/houses/SS Ernest.png',
      jobName: 'Ernest',
      collection: 'Southern Series',
      client: 'Jennian Standard Pricing',
      jobNumber: 'SS10',
      siteAddress: 'none',
      lotNumber: 'none',
      gfa: '167.62m2'
    },
    {
      id: 17,
      date_created: new Date(Date.now()),
      img: 'img/houses/SS George.png',      
      jobName: 'George',
      collection: 'Southern Series',
      client: 'Jennian Standard Pricing',
      jobNumber: 'SS11',
      siteAddress: 'none',
      lotNumber: 'none',
      gfa: '166.04m2'
    },
    {
      id: 18,
      date_created: new Date(Date.now()),
      img: 'img/houses/SS George Architectural.png',      
      jobName: 'George Architectural',
      collection: 'Southern Series',
      client: 'Jennian Standard Pricing',
      jobNumber: 'SS11a',
      siteAddress: 'none',
      lotNumber: 'none',
      gfa: '166.04m2'
    },
    {
      id: 19,
      date_created: new Date(Date.now()),
      img: 'img/houses/SS James.png',      
      jobName: 'James',
      collection: 'Southern Series',
      client: 'Jennian Standard Pricing',
      jobNumber: 'SS12',
      siteAddress: 'none',
      lotNumber: 'none',
      gfa: '164.84m2'
    },
    {
      id: 20,
      date_created: new Date(Date.now()),
      img: 'img/houses/SS James Architectural.png',      
      jobName: 'James Architectural',
      collection: 'Southern Series',
      client: 'Jennian Standard Pricing',
      jobNumber: 'SS12a',
      siteAddress: 'none',
      lotNumber: 'none',
      gfa: '164.84m2'
    },
    {
      id: 21,
      date_created: new Date(Date.now()),
      img: 'img/houses/SS Louis.png',      
      jobName: 'Louis',
      collection: 'Southern Series',
      client: 'Jennian Standard Pricing',
      jobNumber: 'SS13',
      siteAddress: 'none',
      lotNumber: 'none',
      gfa: '157.98m2'
    },
    {
      id: 22,
      date_created: new Date(Date.now()),
      img: 'img/houses/SS Louis Architectural.png',      
      jobName: 'Louis Architectural',
      collection: 'Southern Series',
      client: 'Jennian Standard Pricing',
      jobNumber: 'SS13a',
      siteAddress: 'none',
      lotNumber: 'none',
      gfa: '157.98m2'
    },
    {
      id: 23,
      date_created: new Date(Date.now()),
      img: 'img/houses/SS Louis 2 Architectural.png',      
      jobName: 'Louis 2 Architectural',
      collection: 'Southern Series',
      client: 'Jennian Standard Pricing',
      jobNumber: 'SS13a2',
      siteAddress: 'none',
      lotNumber: 'none',
      gfa: '157.98m2'
    },
    {
      id: 24,
      date_created: new Date(Date.now()),
      img: 'img/houses/SS Louis 3 Architectural.png',      
      jobName: 'Louis 3 Architectural',
      collection: 'Southern Series',
      client: 'Jennian Standard Pricing',
      jobNumber: 'SS13a3',
      siteAddress: 'none',
      lotNumber: 'none',
      gfa: '157.98m2'
    },
    {
      id: 25,
      date_created: new Date(Date.now()),
      img: 'img/houses/SS Mary.png',      
      jobName: 'Mary',
      collection: 'Southern Series',
      client: 'Jennian Standard Pricing',
      jobNumber: 'SS14',
      siteAddress: 'none',
      lotNumber: 'none',
      gfa: '165.25m2'
    },
    {
      id: 26,
      date_created: new Date(Date.now()),
      img: 'img/houses/SS Mary Architectural.png',      
      jobName: 'Mary Architectural',
      collection: 'Southern Series',
      client: 'Jennian Standard Pricing',
      jobNumber: 'SS14a',
      siteAddress: 'none',
      lotNumber: 'none',
      gfa: '165.25m2'
    },
    {
      id: 27,
      date_created: new Date(Date.now()),
      img: 'img/houses/SS Victora.png',      
      jobName: 'Victora',
      collection: 'Southern Series',
      client: 'Jennian Standard Pricing',
      jobNumber: 'SS15',
      siteAddress: 'none',
      lotNumber: 'none',
      gfa: '180.97m2'
    },
    {
      id: 28,
      date_created: new Date(Date.now()),
      img: 'img/houses/SS Victora Architectural.png',      
      jobName: 'Victora Architectural',
      collection: 'Southern Series',
      client: 'Jennian Standard Pricing',
      jobNumber: 'SS15a',
      siteAddress: 'none',
      lotNumber: 'none',
      gfa: '180.97m2'
    },
    {
      id: 29,
      date_created: new Date(Date.now()),
      img: 'img/houses/SS William.png',      
      jobName: 'William',
      collection: 'Southern Series',
      client: 'Jennian Standard Pricing',
      jobNumber: 'SS16',
      siteAddress: 'none',
      lotNumber: 'none',
      gfa: '201.97m2'
    },
    {
      id: 30,
      date_created: new Date(Date.now()),
      img: 'img/houses/SS William Architectural.png',      
      jobName: 'William Architectural',
      collection: 'Southern Series',
      client: 'Jennian Standard Pricing',
      jobNumber: 'SS16a',
      siteAddress: 'none',
      lotNumber: 'none',
      gfa: '201.97m2'
    },
  ])
}




