// return knex.schema.createTable('jobs', (table) => {
//   table.increments('id').primary()
//   table.date('dateCreated')
//   table.string('jobName')
//   table.string('clientName')
//   table.string('siteAddress')
//   table.string('collection')
//   table.string('lotNumber')
//   table.string('jobNumber')
//   table.string('houseType')
//   table.string('gfa')
//   table.string('salesPerson')
//   table.string('imageCover')
//   table.string('budget')
//   table.integer('deposit')
//   table.integer('retailPrice')
//   table.integer('contractPrice')
//   })  
exports.seed = (knex, Promise) => {
  return knex('jobs').insert([
    {
      id: 0,
      dateCreated: new Date(Date.now()),
      jobName: 'Alexandra',
      clientName: 'Client 01',
      siteAddress: '01 Fake Street',
      collection: 'Southern Series',
      lotNumber: 'Lot 01',
      jobNumber: 'SS01',
      houseType: 'DESIGN/BUILD',
      gfa: '170.69m2',
      salesPerson: 'Standard Pricing',
      imageCover: '../img/houses/alexandra/alexandra.png',
      budget: '400K',
      deposit: 5000,
      retailPrice: 396600.00,
      contractPrice: 396600.00
    },
    {
      id: 1,
      dateCreated: new Date(Date.now()),
      jobName: 'Andrew',
      clientName: 'Client 02',
      siteAddress: '02 Fake Street',
      collection: 'Southern Series',
      lotNumber: 'Lot 02',
      jobNumber: 'SS02',
      houseType: 'DESIGN/BUILD',
      gfa: '148.56m2',
      salesPerson: 'Standard Pricing',
      imageCover: '../img/houses/andrew/andrew.png',
      budget: '350K',
      deposit: 5000,
      retailPrice: 347690.00,
      contractPrice: 347690.00
    },
    {
      id: 2,
      dateCreated: new Date(Date.now()),
      jobName: 'Anne',
      clientName: 'Client 03',
      siteAddress: '03 Fake Street',
      collection: 'Southern Series',
      lotNumber: 'Lot 03',
      jobNumber: 'SS03',
      houseType: 'DESIGN/BUILD',
      gfa: '166.12m2',
      salesPerson: 'Standard Pricing',
      imageCover: '../img/houses/anne/anne.png',
      budget: '350K',
      deposit: 5000,
      retailPrice: 386565.00,
      contractPrice: 386565.00
    },
    {
      id: 3,
      dateCreated: new Date(Date.now()),
      jobName: 'Catherine',
      clientName: 'Client 04',
      siteAddress: '04 Fake Street',
      collection: 'Southern Series',
      lotNumber: 'Lot 04',
      jobNumber: 'SS04',
      houseType: 'DESIGN/BUILD',
      gfa: '111.08m2',
      salesPerson: 'Standard Pricing',
      imageCover: '../img/houses/catherine/catherine.png',
      budget: '300K',
      deposit: 5000,
      retailPrice: 287079.00,
      contractPrice: 287079.00
    },
    {
      id: 4,
      dateCreated: new Date(Date.now()),
      jobName: 'Charles',
      clientName: 'Client 05',
      siteAddress: '05 Fake Street',
      collection: 'Southern Series',
      lotNumber: 'Lot 05',
      jobNumber: 'SS05',
      houseType: 'DESIGN/BUILD',
      gfa: '181.76m2',
      salesPerson: 'Standard Pricing',
      imageCover: '../img/houses/charles/charles.png',
      budget: '400K',
      deposit: 5000,
      retailPrice: 410903.00,
      contractPrice: 410903.00,
    },
    {
      id: 5,
      dateCreated: new Date(Date.now()),
      jobName: 'Charlotte',
      clientName: 'Client 06',
      siteAddress: '06 Fake Street',
      collection: 'Southern Series',
      lotNumber: 'Lot 06',
      jobNumber: 'SS06',
      houseType: 'DESIGN/BUILD',
      gfa: '135.37m2',
      salesPerson: 'Standard Pricing',
      imageCover: '../img/houses/charlotte/charlotte.png',
      budget: '350K',
      deposit: 5000,
      retailPrice: 339160.00,
      contractPrice: 339160.00,
    },
    {
      id: 6,
      dateCreated: new Date(Date.now()),
      jobName: 'Edward 2',
      clientName: 'Client 07',
      siteAddress: '07 Fake Street',
      collection: 'Southern Series',
      lotNumber: 'Lot 07',
      jobNumber: 'SS07',
      houseType: 'DESIGN/BUILD',
      gfa: '106.41m2',
      salesPerson: 'Standard Pricing',
      imageCover: '../img/houses/edward_2/edward_2.png',
      budget: '300K',
      deposit: 5000,
      retailPrice: 281894.00,
      contractPrice: 281894.00,
    },
    {
      id: 7,
      dateCreated: new Date(Date.now()),
      jobName: 'Edward 3',
      clientName: 'Client 08',
      siteAddress: '08 Fake Street',
      collection: 'Southern Series',
      lotNumber: 'Lot 08',
      jobNumber: 'SS08',
      houseType: 'DESIGN/BUILD',
      gfa: '120.22m2',
      salesPerson: 'Standard Pricing',
      imageCover: '../img/houses/edward_3/edward_3.png',
      budget: '320K',
      deposit: 5000,
      retailPrice: 318056.00,
      contractPrice: 318056.00,
    },
    {
      id: 8,
      dateCreated: new Date(Date.now()),
      jobName: 'Edward 4',
      clientName: 'Client 09',
      siteAddress: '09 Fake Street',
      collection: 'Southern Series',
      lotNumber: 'Lot 09',
      jobNumber: 'SS09',
      houseType: 'DESIGN/BUILD',
      gfa: '132.71m2',
      salesPerson: 'Standard Pricing',
      imageCover: '../img/houses/edward_4/edward_4.png',
      budget: '350K',
      deposit: 5000,
      retailPrice: 338712.00,
      contractPrice: 338712.00,
    },
    {
      id: 9,
      dateCreated: new Date(Date.now()),
      jobName: 'Ernet',
      clientName: 'Client 10',
      siteAddress: '10 Fake Street',
      collection: 'Southern Series',
      lotNumber: 'Lot 10',
      jobNumber: 'SS10',
      houseType: 'DESIGN/BUILD',
      gfa: '166.04m2',
      salesPerson: 'Standard Pricing',
      imageCover: '../img/houses/ernest/ernest.png',
      budget: '400k',
      deposit: 5000,
      retailPrice: 384059.00,
      contractPrice: 384059.00,
    },
    {
      id: 10,
      dateCreated: new Date(Date.now()),
      jobName: 'George',
      clientName: 'Client 11',
      siteAddress: '11 Fake Street',
      collection: 'Southern Series',
      lotNumber: 'Lot 11',
      jobNumber: 'SS11',
      houseType: 'DESIGN/BUILD',
      gfa: '166.04m2',
      salesPerson: 'Standard Pricing',
      imageCover: '../img/houses/geroge/george.png',
      budget: '400k',
      deposit: 5000,
      retailPrice: 382386.00,
      contractPrice: 382386.00,
    },
    {
      id: 11,
      dateCreated: new Date(Date.now()),
      jobName: 'James',
      clientName: 'Client 12',
      siteAddress: '12 Fake Street',
      collection: 'Southern Series',
      lotNumber: 'Lot 12',
      jobNumber: 'SS12',
      houseType: 'DESIGN/BUILD',
      gfa: '164.84m2',
      salesPerson: 'Standard Pricing',
      imageCover: '../img/houses/james/james.png',
      budget: '400k',
      deposit: 5000,
      retailPrice: 374792.00,
      contractPrice: 374972.00,
    },
    {
      id: 12,
      dateCreated: new Date(Date.now()),
      jobName: 'Louis',
      clientName: 'Client 13',
      siteAddress: '13 Fake Street',
      collection: 'Southern Series',
      lotNumber: 'Lot 13',
      jobNumber: 'SS13',
      houseType: 'DESIGN/BUILD',
      gfa: '158.11m2',
      salesPerson: 'Standard Pricing',
      imageCover: '../img/houses/louis/louis.png',
      budget: '400k',
      deposit: 5000,
      retailPrice: 375133.00,
      contractPrice: 375133.00,
    },
    {
      id: 13,
      dateCreated: new Date(Date.now()),
      jobName: 'Mary',
      clientName: 'Client 14',
      siteAddress: '14 Fake Street',
      collection: 'Southern Series',
      lotNumber: 'Lot 14',
      jobNumber: 'SS14',
      houseType: 'DESIGN/BUILD',
      gfa: '165.25m2',
      salesPerson: 'Standard Pricing',
      imageCover: '../img/houses/mary/mary.png',
      budget: '400k',
      deposit: 5000,
      retailPrice: 364510.00,
      contractPrice: 364510.00,
    },
    {
      id: 14,
      dateCreated: new Date(Date.now()),
      jobName: 'Victoria',
      clientName: 'Client 15',
      siteAddress: '15 Fake Street',
      collection: 'Southern Series',
      lotNumber: 'Lot 15',
      jobNumber: 'SS15',
      houseType: 'DESIGN/BUILD',
      gfa: '180.97m2',
      salesPerson: 'Standard Pricing',
      imageCover: '../img/houses/victoria/victoria.png',
      budget: '400k',
      deposit: 5000,
      retailPrice: 392262.00,
      contractPrice: 392262.00,
    },
    {
      id: 15,
      dateCreated: new Date(Date.now()),
      jobName: 'William',
      clientName: 'Client 16',
      siteAddress: '16 Fake Street',
      collection: 'Southern Series',
      lotNumber: 'Lot 16',
      jobNumber: 'SS16',
      houseType: 'DESIGN/BUILD',
      gfa: '201.97m2',
      salesPerson: 'Standard Pricing',
      imageCover: '../img/houses/william/william.png',
      budget: '450k',
      deposit: 5000,
      retailPrice: 428062.00,
      contractPrice: 428062.00,
    },
  ])
}







